import { Linter } from "eslint";

export const standardRules: Linter.RulesRecord = {
  "no-console": "error",
  "no-debugger": "error",
  curly: "off",
  indent: "off",
  semi: "off",
  "comma-dangle": ["error", "always-multiline"],
  "comma-spacing": ["error", { before: false, after: true }],
  "key-spacing": ["error", { afterColon: true }],
  "object-curly-spacing": ["error", "always"],
  "arrow-parens": ["error", "as-needed"],
  camelcase: "off",
  "max-len": "off",
  "antfu/top-level-function": "off",
  "@typescript-eslint/no-explicit-any": "off",
  "n/prefer-global/process": ["off"],
  "sonarjs/cognitive-complexity": ["off"],
  "newline-before-return": "error",
  "lines-around-comment": [
    "error",
    {
      beforeBlockComment: true,
      beforeLineComment: true,
      allowBlockStart: true,
      allowClassStart: true,
      allowObjectStart: true,
      allowArrayStart: true,
      ignorePattern: "!SECTION",
    },
  ],
  "@typescript-eslint/no-unused-vars": [
    "error",
    { varsIgnorePattern: "^_+$", argsIgnorePattern: "^_+$" },
  ],
  "array-element-newline": ["error", "consistent"],
  "array-bracket-newline": ["error", "consistent"],
  "padding-line-between-statements": [
    "error",
    { blankLine: "always", prev: "expression", next: "const" },
    { blankLine: "always", prev: "const", next: "expression" },
    { blankLine: "always", prev: "multiline-const", next: "*" },
    { blankLine: "always", prev: "*", next: "multiline-const" },
  ],
  "import/prefer-default-export": "off",
  "import/newline-after-import": ["error", { count: 1 }],
  "import/extensions": [
    "error",
    "ignorePackages",
    { js: "never", jsx: "never", ts: "never", tsx: "never" },
  ],
  "import/no-unresolved": [
    2,
    {
      ignore: ["~pages$", "virtual:generated-layouts", ".*\\?raw", "#auth$"],
    },
  ],
  "no-restricted-imports": [
    "error",
    "vuetify/components",
    { name: "vue3-apexcharts", message: "apexcharts are autoimported" },
  ],
  "no-shadow": "off",
  "@typescript-eslint/no-shadow": ["error"],
  "@typescript-eslint/consistent-type-imports": "error",

  // Vue rules (plugin registered below)
  "vue/multi-word-component-names": "off",
  "vue/require-default-prop": "off",
  "vue/first-attribute-linebreak": [
    "error",
    { singleline: "beside", multiline: "below" },
  ],
  "vue/block-tag-newline": "error",
  "vue/component-api-style": "error",
  "vue/component-name-in-template-casing": [
    "error",
    "PascalCase",
    { registeredComponentsOnly: false, ignores: ["/^swiper-/"] },
  ],
  "vue/custom-event-name-casing": [
    "error",
    "camelCase",
    { ignores: ['"/^(click):[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?/"'] },
  ],
  "vue/define-macros-order": "error",
  "vue/html-comment-content-newline": "error",
  "vue/html-comment-content-spacing": "error",
  "vue/html-comment-indent": "error",
  "vue/match-component-file-name": "error",
  "vue/no-child-content": "error",
  "vue/no-duplicate-attr-inheritance": "error",
  "vue/no-empty-component-block": "error",
  "vue/no-multiple-objects-in-class": "error",
  "vue/no-reserved-component-names": "error",
  "vue/no-template-target-blank": "error",
  "vue/no-useless-mustaches": "error",
  "vue/no-useless-v-bind": "error",
  "vue/padding-line-between-blocks": "error",
  "vue/prefer-separate-static-class": "error",
  "vue/prefer-true-attribute-shorthand": "off",
  "vue/v-on-handler-style": "error",
  "vue/no-restricted-class": ["error", "/^(p|m)(l|r)-/"],
  "vue/valid-v-slot": ["error", { allowModifiers: true }],
  "vue/no-irregular-whitespace": "error",
  "vue/template-curly-spacing": "error",

  // SonarJS & Promise
  "sonarjs/no-duplicate-string": "off",
  "sonarjs/no-nested-template-literals": "off",
  "promise/always-return": "off",
  "promise/catch-or-return": "off",
};
